language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov

script:
  # Build the project and run tests
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
  - make all
  - bin/run_tests

after_success:
  # Create lcov report
  - lcov --capture --directory . --output-file coverage.info
  # Remove external libraries from coverage information file
  - lcov --remove coverage.info '/usr/*' '*gtest*' --output-file coverage.info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

